namespace notifgram.Core;
public enum FcmKeys
{
  //TEXT_TYPE,
  TEXT_CONTENT,
  FILE_NAME,
  FILE_CHUNK_INDEX,
  FILE_TOTAL_CHUNKS,
  FILE_CHUNK_DATA,
  NOTIFICATION_TITLE,
  NOTIFICATION_BODY,
  JSON_POST,
  JSON_ALL_CHANNEL,
  DELETED_POST,
  DELETED_CHANNEL,
  //OBJECT_ID,

}
